version: "3"
services:
  api-backend:
    build: ./backend
    ports:
      - "9000:5000"
    networks:
      - api-app

  react-frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - "1000:3000"
    networks:
      - api-app
    depends_on:
      - api-backend

networks:
  api-app:
    driver: bridge
